export const AchievementsConfig = [
  {
    id: "newbie",
    title: "Новичок",
    description: "Сыграть первую игру",
    icon: "👶",
    reward: 50,
    condition: (stats) => stats.gamesPlayed >= 1,
    rarity: "common",
    hidden: false,
  },
  {
    id: "first_win",
    title: "Первая победа",
    description: "Одержать первую победу в игре",
    icon: "🏆",
    reward: 100,
    condition: (stats) => stats.wins >= 1,
    rarity: "common",
    hidden: false,
  },
  {
    id: "fast_win",
    title: "Скоростная игра",
    description: "Победить менее чем за 5 минут",
    icon: "⏱️",
    reward: 250,
    condition: (stats) => stats.fastestWin <= 300,
    rarity: "uncommon",
    hidden: false,
  },
  {
    id: "perfect_game",
    title: "Идеальная игра",
    description: "Победить за минимальное количество ходов",
    icon: "✨",
    reward: 500,
    condition: (stats) => stats.moves === stats.minPossibleMoves,
    rarity: "rare",
    hidden: true,
  },
  {
    id: "foundation_master",
    title: "Мастер фундаментов",
    description: "Переместить 50 карт в фундаменты",
    icon: "🔼",
    reward: 200,
    condition: (stats) => stats.cardsToFoundation >= 50,
    rarity: "uncommon",
    hidden: false,
    getProgress: (stats) => ({
      current: stats.cardsToFoundation,
      target: 50,
    }),
  },
  {
    id: "score_breaker",
    title: "Рекордсмен",
    description: "Набрать 1000 очков в одной игре",
    icon: "💯",
    reward: 300,
    condition: (stats) => stats.highestScore >= 1000,
    rarity: "rare",
    hidden: false,
  },
  {
    id: "card_flipper",
    title: "Переворачиватель",
    description: "Перевернуть 100 карт",
    icon: "🔄",
    reward: 150,
    condition: (stats) => stats.cardsFlipped >= 100,
    rarity: "common",
    hidden: false,
    getProgress: (stats) => ({
      current: stats.cardsFlipped,
      target: 100,
    }),
  },
  {
    id: "persistent_player",
    title: "Упорный игрок",
    description: "Сыграть 20 игр",
    icon: "🎮",
    reward: 200,
    condition: (stats) => stats.gamesPlayed >= 20,
    rarity: "uncommon",
    hidden: false,
    getProgress: (stats) => ({
      current: stats.gamesPlayed,
      target: 20,
    }),
  },
  {
    id: "hint_saver",
    title: "Экономный",
    description: "Победить, не используя подсказки",
    icon: "💡",
    reward: 180,
    condition: (stats) => stats.winsWithoutHints >= 1,
    rarity: "rare",
    hidden: true,
  },
  {
    id: "win_streak",
    title: "Серия побед",
    description: "Одержать 3 победы подряд",
    icon: "🔥",
    reward: 350,
    condition: (stats) => stats.currentWinStreak >= 3,
    rarity: "rare",
    hidden: true,
    getProgress: (stats) => ({
      current: stats.currentWinStreak,
      target: 3,
    }),
  },
  {
    id: "tableau_cleaner",
    title: "Чистильщик таблиц",
    description: "Очистить одну из таблиц полностью",
    icon: "🧹",
    reward: 150,
    condition: (stats) => stats.tableausCleared >= 1,
    rarity: "uncommon",
    hidden: false,
  },
  {
    id: "undo_avoider",
    title: "Решительный",
    description: "Победить, не используя отмену хода",
    icon: "⏮️",
    reward: 200,
    condition: (stats) => stats.winsWithoutUndo >= 1,
    rarity: "uncommon",
    hidden: true,
  },
  {
    id: "veteran_player",
    title: "Ветеран",
    description: "Сыграть 100 игр",
    icon: "👴",
    reward: 500,
    condition: (stats) => stats.gamesPlayed >= 100,
    rarity: "epic",
    hidden: false,
    getProgress: (stats) => ({
      current: stats.gamesPlayed,
      target: 100,
    }),
  },
  {
    id: "king_of_cards",
    title: "Король карт",
    description: "Одержать 50 побед",
    icon: "👑",
    reward: 1000,
    condition: (stats) => stats.wins >= 50,
    rarity: "epic",
    hidden: false,
    getProgress: (stats) => ({
      current: stats.wins,
      target: 50,
    }),
  },
];

export const AchievementsRarities = {
  common: {
    name: "Обычное",
    color: "#95a5a6",
    chance: 0.6,
  },
  uncommon: {
    name: "Необычное",
    color: "#2ecc71",
    chance: 0.25,
  },
  rare: {
    name: "Редкое",
    color: "#3498db",
    chance: 0.1,
  },
  epic: {
    name: "Эпическое",
    color: "#9b59b6",
    chance: 0.04,
  },
  legendary: {
    name: "Легендарное",
    color: "#f1c40f",
    chance: 0.01,
  },
};
