export const ShopConfig = {
  categories: {
    cardFaces: {
      id: "cardFaces",
      name: "Лица карт",
      icon: "♠️",
      enabled: true,
    },
    cardBacks: {
      id: "cardBacks",
      name: "Рубашки",
      icon: "🃏",
      enabled: true,
    },
    backgrounds: {
      id: "backgrounds",
      name: "Фоны",
      icon: "🎨",
      enabled: true,
    },
    specialEffects: {
      id: "specialEffects",
      name: "Эффекты",
      icon: "✨",
      enabled: false, // Будет добавлено в будущем
    },
  },

  items: [
    // === Лица карт ===
    {
      id: "classic_faces",
      name: "Классические",
      type: "faces",
      category: "cardFace",
      owned: false,
      isBought: false,
      price: 0,
      styleClass: "classic-faces",
      description: "Стандартный дизайн карт",
      rarity: "common",
      unlockCondition: null,
      previewImage: "",
      styles: {
        background: "rgb(204, 195, 195)",
      },
    },
    {
      id: "cosmo_faces",
      name: "Космо стиль",
      type: "faces",
      category: "cardFace",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "cosmo-faces",
      description: "Космический стиль",
      rarity: "uncommon",
      unlockCondition: { wins: 5 },
      previewImage: "",
      styles: {
        background: `radial-gradient(circle at center, #000428, #004e92),
          url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='30' cy='30' r='1' fill='white'/%3E%3Ccircle cx='80' cy='120' r='1' fill='white'/%3E%3C/svg%3E")`,
        color: "white",
      },
    },
    // {
    //   id: "neon_faces",
    //   name: "Неоновый стиль",
    //   type: "faces",
    //   category: "cardFace",
    //   price: 200,
    //   styleClass: "neon-faces",
    //   description: "Красивый неоновый стиль",
    //   rarity: "uncommon",
    //   unlockCondition: { wins: 5 },
    //   previewImage: "assets/shop/previews/neon_faces.png",
    // },
    // {
    //   id: "metal_faces",
    //   name: "Холодный металл",
    //   type: "faces",
    //   category: "cardFace",
    //   price: 200,
    //   styleClass: "metal-faces",
    //   description: "Охлаждающий, но не пыл, стиль",
    //   rarity: "uncommon",
    //   unlockCondition: { wins: 5 },
    //   previewImage: "assets/shop/previews/metal_faces.png",
    // },
    {
      id: "leather_faces",
      name: "Кожаный стиль",
      type: "faces",
      category: "cardFace",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "leather-faces",
      description: "Очень приятный стиль",
      rarity: "uncommon",
      unlockCondition: { wins: 5 },
      previewImage: "",
      styles: {
        background: `radial-gradient(circle at 70% 30%, #f5e7d0 0%, #e6d5b8 100%),
          url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'><path fill='rgba(139,69,19,0.1)' d='M0 0h100v100H0z'/></svg>")`,
        border: "2px solid #8b4513",
        color: "#5a3921",
        boxShadow: "inset 0 0 20px rgba(139, 69, 19, 0.3)",
      },
    },
    {
      id: "liquid_metal_faces",
      name: "Жидкий металл",
      type: "faces",
      category: "cardFace",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "liquid-metal-faces",
      description: "Ускользающий стиль",
      rarity: "uncommon",
      unlockCondition: { wins: 5 },
      previewImage: "assets/shop/previews/liquid_metal_faces.png",
      styles: {
        background: `linear-gradient(135deg,rgba(200, 200, 200, 0.8) 0%,rgba(150, 150, 150, 0.9) 50%,rgba(200, 200, 200, 0.8) 100%)`,
        boxShadow: `0 0 10px rgba(255, 255, 255, 0.8), inset 0 0 10px rgba(0, 0, 0, 0.2)`,
        border: "none",
        position: "relative",
        overflow: "hidden",
      },
    },
    {
      id: "vintage_faces",
      name: "Винтажные",
      type: "faces",
      category: "cardFace",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "vintage-faces",
      description: "Старинный стиль XIX века",
      rarity: "uncommon",
      unlockCondition: { wins: 5 },
      previewImage: "assets/shop/previews/vintage_faces.png",
      styles: {
        background: "#f5f0e1",
        borderRadius: "5px",
        boxShadow: `0 2px 5px rgba(0, 0, 0, 0.3), inset 1px 1px 0 rgba(255, 255, 255, 0.3), inset -1px -1px 0 rgba(0, 0, 0, 0.1)`,
        backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(0, 0, 0, 0.05) 1px, transparent 1px)`,
        backgroundSize: "20px 20px",
        clipPath: `polygon(0 3%, 3% 0, 97% 0, 100% 3%, 100% 97%, 97% 100%, 3% 100%, 0% 97%)`,
        filter: "sepia(30%) brightness(95%)",
      },
    },

    // === Рубашки карт ===
    {
      id: "classic_back",
      name: "Классическая рубашка",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 0,
      styleClass: "classic-back",
      description: "Классическая рубашка",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        background:
          "repeating-linear-gradient(45deg,#1a5a1a,#1a5a1a 10px,#165016 10px,#165016 20px)",
        color: "transparent !important",
      },
    },
    {
      id: "dice_back",
      name: "Игральные кости",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "dice-back",
      description: "Много игральных костей",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        backgroundColor: "#fff",
        backgroundImage: ` radial-gradient(#000 20%, transparent 20%), radial-gradient(#000 20%, transparent 20%)`,
        backgroundSize: "20px 20px",
        backgroundPosition: "0 0, 10px 10px",
      },
    },
    {
      id: "goldV_back",
      name: "Золотая рубашка",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "goldV-back",
      description: "Золотая рубашка",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        backgroundColor: "#d4af37",
        backgroundImage: `radial-gradient(circle at 10% 20%, rgba(255, 255, 255, 0.3) 0%, transparent 20%),
          radial-gradient(circle at 90% 80%, rgba(255, 255, 255, 0.3) 0%, transparent 20%)`,
      },
    },
    {
      id: "treeB_back",
      name: "Деревянный стиль",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "treeB-back",
      description: "Деревянный стиль рубашек",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        backgroundColor: "#8b4513",
        backgroundImage: `linear-gradient(to right, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px, transparent 1px, transparent 100%),
          linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px,transparent 1px,transparent 100%)`,
        backgroundSize: "10px 10px",
      },
    },
    {
      id: "elegantRed_back",
      name: "Элегантно-красный стиль",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "elegantRed-back",
      description: "Элегантно-красный стиль",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        background: `repeating-linear-gradient(45deg,#8b0000,#8b0000 10px,#6b0000 10px,#6b0000 20px)`,
        boxShadow: "inset 0 0 10px rgba(0, 0, 0, 0.5)",
      },
    },
    {
      id: "elegantBlue_back",
      name: "Элегантно-синий стиль",
      type: "backs",
      category: "cardBack",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "elegantBlue-back",
      description: "Элегантно-синий стиль",
      rarity: "common",
      unlockCondition: null,
      previewImage: "assets/shop/previews/blue_back.png",
      styles: {
        background: `repeating-linear-gradient(45deg,#00008b,#00008b 10px,#00006b 10px,#00006b 20px)`,
        boxShadow: "inset 0 0 10px rgba(58, 8, 236, 0.5)",
      },
    },

    // === Фоны ===
    {
      id: "classic_fon",
      name: "Классический зелёный",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 0,
      styleClass: "classic-fon",
      description: "Классический фон",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        backgroundColor: "green",
        width: "326px",
        height: "245px",
      },
    },
    {
      id: "light_green_fon",
      name: "Классический светло-зелёный",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 0,
      styleClass: "light-green-fon",
      description: "Классический светло-зелёный",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        backgroundColor: "rgb(104, 189, 104)",
        width: "326px",
        height: "245px",
      },
    },
    {
      id: "classic_fon_2",
      name: "Классический 2",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-2",
      description: "Классический 2",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        background: `linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab)`,
        backgroundSize: "400% 400%",
        animation: "gradientBG 15s ease infinite",
      },
    },
    {
      id: "classic_fon_3",
      name: "Классический 3",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-3",
      description: "Классический 3",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        background: `linear-gradient(#2b2b44 2px, transparent 2px),
    linear-gradient(90deg, #2b2b44 2px, transparent 2px),
    linear-gradient(#3b3b5a 1px, transparent 1px),
    linear-gradient(90deg, #3b3b5a 1px, #1a1a2e 1px)`,
        backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
        backgroundPosition: "-2px -2px, -2px -2px, -1px -1px, -1px -1px",
      },
    },
    {
      id: "classic_fon_4",
      name: "Классический 4",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-4",
      description: "Классический 4",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        background: `radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent),
    radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent) 50px 50px,
    linear-gradient(#2d2d2d 2px, transparent 2px) 0 -1px,
    linear-gradient(90deg, #2d2d2d 2px, #1a1a1a 2px) -1px 0`,
        backgroundSize: "100px 100px, 100px 100px, 50px 50px, 50px 50px",
        backgroundColor: "#1a1a1a",
      },
    },
    {
      id: "classic_fon_5",
      name: "Классический 5",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-5",
      description: "Классический 5",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        background: `linear-gradient(135deg, 
      rgba(100,149,237,0.1) 0%, 
      rgba(100,149,237,0) 50%, 
      rgba(100,149,237,0.1) 100%
    ),
    linear-gradient(45deg, 
      rgba(255,255,255,0.05) 1px, 
      transparent 1px
    ),
    linear-gradient(-45deg, 
      rgba(255,255,255,0.05) 1px, 
      transparent 1px
    )`,
        backgroundSize: "100% 100%, 30px 30px, 30px 30px",
        backgroundColor: "#0a1a2f",
      },
    },
    {
      id: "classic_fon_6",
      name: "Классический 6",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-6",
      description: "Классический 6",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        backgroundColor: "#52411b",
        backgroundImage: `linear-gradient(to bottom, 
          rgba(0, 0, 0, 0.589) 0%,
      transparent 80%
    ),
    url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><path fill="none" stroke="rgba(0,0,0,0.05)" stroke-width="2.5" d="M0,0 L100,0 L100,100 L0,100 Z M10,10 C40,10 60,40 90,40 M10,60 C40,60 60,30 90,30"/></svg>')`,
        backgroundSize: "100% 100%, 100px 100px",
      },
    },
    {
      id: "classic_fon_7",
      name: "Классический 7",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "classic-fon-7",
      description: "Классический 7",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "",
      styles: {
        width: "326px",
        height: "245px",
        background: `conic-gradient(from 90deg at 1px 1px, 
        transparent 25%, 
        #8a2be2 0%, 
        #8a2be2 50%, 
        transparent 0%, 
        transparent 75%, 
        #4b0082 0%
        )`,
        backgroundColor: " #1e0036",
        backgroundSize: "25px 25px",
      },
    },
    {
      id: "green_path_fon",
      name: "Tропа",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "green-path-fon",
      description: "Тропа в тоннеле из деревьев",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "./src/assets/shop/fons/fon_1_1.jpg",
    },
    {
      id: "green_field_fon",
      name: "Поле",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "green-field-fon",
      description: "Красивое небо над полем",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "./src/assets/shop/fons/fon_2_1.jpg",
    },
    {
      id: "green_field2_fon",
      name: "Поле 2",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "green-field2-fon",
      description: "Красивое небо над полем",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "./src/assets/shop/fons/fon_3_1.jpg",
    },
    {
      id: "green_field3_fon",
      name: "Поле 3",
      type: "backgrounds",
      category: "background",
      owned: false,
      isBought: false,
      price: 5,
      styleClass: "green-field3-fon",
      description: "Красивое небо над полем",
      rarity: "rare",
      unlockCondition: { score: 1000 },
      previewImage: "./src/assets/shop/fons/fon_4_1.jpg",
    },
  ],

  currencies: {
    coins: {
      name: "Монеты",
      icon: "🪙",
      exchangeRate: 1,
    },
    gems: {
      name: "Кристаллы",
      icon: "💎",
      exchangeRate: 100,
      premium: true,
    },
  },

  rarities: {
    common: {
      name: "Обычный",
      color: "#a0a0a0",
    },
    uncommon: {
      name: "Необычный",
      color: "#2ecc71",
    },
    rare: {
      name: "Редкий",
      color: "#3498db",
    },
    epic: {
      name: "Эпический",
      color: "#9b59b6",
    },
    legendary: {
      name: "Легендарный",
      color: "#f1c40f",
    },
  },

  defaultShopState: {
    currentCategory: "faces",
    purchasedItems: [],
    selectedItems: {
      cardFace: "classic_faces",
      cardBack: "blue_back",
      background: "green_felt",
    },
  },

  defaultItems: {
    cardFace: "classic_faces",
    cardBack: "blue_back",
    background: "default_bg",
  },
};
